spring:
    data:
        jpa:
            repositories:
                enabled: true
    jpa:
        database-platform: org.hibernate.dialect.MySQL8Dialect
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                "[format_sql]": true
    datasource:
        url: jdbc:mysql://localhost:3306/easybank
        username: root
        password: root
        driver-class-name: com.mysql.cj.jdbc.Driver
      
      